<a href="https://colab.research.google.com/github/isidoreduc/02456-deep-learning-with-PyTorch/blob/master/Math_for_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [10]:
import numpy as np
# create an array in numpy, can specify data type also
a = np.array([[1,2,3], [4,5,6]], dtype="int32")
print(a)
print(a.dtype)
a.shape

[[1 2 3]
 [4 5 6]]
int32


(2, 3)

In [15]:
# 2D arrays filles with 0s or 1s
b = np.zeros((3,4), dtype="uint32")
b
b[0,3], b[2,2] = 23, 42
b

array([[ 0,  0,  0, 23],
       [ 0,  0,  0,  0],
       [ 0,  0, 42,  0]], dtype=uint32)

In [20]:
c = 15 * np.ones((3,3), dtype="int16")
print(c)
d = np.ones((1))
d

[[15 15 15]
 [15 15 15]
 [15 15 15]]


array([1.])

In [22]:
# arange function is range from python
d = np.arange(12).reshape((4,3))
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
#  numpy uses : to specify all elements over a specific dimmension (row/column)
# print first 2 columns
print(d[:, :2])
print("\n")
# print first 2 rows and first 2 columns
print(d[:2, :2])


[[ 0  1]
 [ 3  4]
 [ 6  7]
 [ 9 10]]


[[0 1]
 [3 4]]


In [43]:
e = np.arange(16)
# extract even numbers
print(e[::2])
# divisible by 3
print(e[::3])
# reverse order
print(e[::-1])
# reverse order 2
print(e[::-2])

[ 0  2  4  6  8 10 12 14]
[ 0  3  6  9 12 15]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[15 13 11  9  7  5  3  1]


In [49]:
f = np.arange(24).reshape(4,2,3)
print(f)
# change second 2D array
f[1,...] = 22 * np.ones((2,3))
print(f)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[22 22 22]
  [22 22 22]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [56]:
# save to disk
g = np.random.randint(2,7, (3,3))
np.save("random_3by3.npy",g)
h = np.load("random_3by3.npy")
h

array([[3, 6, 5],
       [3, 6, 5],
       [3, 3, 3]])

# SciPy

In [ ]:
import scipy
